name: Build, Test, and Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required for GitVersion to work properly

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      # Install and run GitVersion to determine the version
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: "5.x"

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.10.2
        id: gitversion
        with:
          useConfigFile: true
          configFilePath: GitVersion.json

      # Display the version for debugging
      - name: Display GitVersion outputs
        run: |
          echo "Major: ${{ steps.gitversion.outputs.major }}"
          echo "Minor: ${{ steps.gitversion.outputs.minor }}"
          echo "Patch: ${{ steps.gitversion.outputs.patch }}"
          echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
          echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
          echo "NuGetVersion: ${{ steps.gitversion.outputs.nuGetVersion }}"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build with version
        run: dotnet build --no-restore -p:Version=${{ steps.gitversion.outputs.nuGetVersion }}

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Pack with version
        run: dotnet pack --no-build --configuration Release -p:Version=${{ steps.gitversion.outputs.nuGetVersion }} -p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersion }}

      # Only publish to NuGet when pushing to main (not on PR)
      - name: Publish to NuGet
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: dotnet nuget push "**/Release/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
